# Providers configuration - specifies AI models and their settings

  - id: openai:gpt-4o-mini
    # config:
    #   temperature: 0.7
    #   max_tokens: 1000

  - id: openai:gpt-4
    # config:
    #   temperature: 0.7
    #   max_tokens: 1000
